FROM python:3.9
WORKDIR /backend

RUN apt-get update && apt-get install -y vim
ADD backend/main.py .

EXPOSE 8080
EXPOSE 5672

RUN pip install web.py pika websockets asyncio

CMD ["python", "./main.py" , "8000"]
